# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c6003a6c333ada60803ea8033d84600d68c7f4485b02e4867b6ddecb326d3e228a25cf2bb0feffb84e408616e0fb9c3e1ac36e497f01d494c02d89b753fb2de

test:
  secret_key_base: 566ea599e8c7a2b397493bd924f018c5c9b61c45f1cf4c2ea139f93b70b4399125dbfb51fa48800065d6a6190eb765910c956c017377a5d464747238e82a5cca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
